spring.application.name=ai-advisor-service
server.port=8086

# OpenAI API Key
openai.api.key=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
openai.api.url=https://api.groq.com/openai/v1/chat/completions
openai.model=llama-3.3-70b-versatile

# JWT
jwt.secret=finlife_super_secret_key_2026_mohanaa
jwt.expiration=86400000